### ISSUE TITLE
Slider exception while trying to open settings

### ISSUE THREAD

**Issue by VBismuth** [Seeneva/seeneva-reader-android#52]
While reading any comic book (tested CBR, PDF and CBZ formats) with system brightness more than 20% and trying to open comic settings (tapping on gear icon), JVM trowing an exception:
[Seeneva_slider_exception.txt](https://github.com/Seeneva/seeneva-reader-android/files/6787133/Seeneva_slider_exception.txt)

Because of system brightness slider value can be greater than the upper threshold, and this causes the problem.

If one tries to use app brightness, it crashes:
[Seeneva_brightness_crash.txt](https://github.com/Seeneva/seeneva-reader-android/files/6787284/Seeneva_brightness_crush.txt)

**App version**: Seeneva 0.1.0-fdroid
**OS**: Android 9, MIUI 11

**Comment by Zellius** [comment]
@VBismuth, thank you! 

> If one tries to use app brightness, it crashes:
> Seeneva_brightness_crash.txt

This one is already fixed in #42 but fix is not published yet.

> While reading any comic book (tested CBR, PDF and CBZ formats) with system brightness more than 20% and trying to open comic settings (tapping on gear icon), JVM trowing an exception:
> Seeneva_slider_exception.txt

I will fix it and include it into **0.1.1** release 👍

**Comment by Zellius** [comment]
@VBismuth if you have a moment could you please test fixed APK version from the [PR artifacts](https://github.com/Seeneva/seeneva-reader-android/actions/runs/1035397185)?
