### ISSUE TITLE
How to guide?

### ISSUE THREAD

**Issue by ObiSandwich** [Seeneva/seeneva-reader-android#70]
Looked every where and cant work out how to import a comic to this app :(

Your website uses the Pepper & Carrot web comic as an example, but can only find JPG files on: https://www.peppercarrot.com/en/

Do you have a How-To setup guide with pictures for Pepper & Carrot please?

**Comment by ObiSandwich** [comment]
I got a nice reply on Mastodon from the creator of Pepper & Carrot, but he couldn't help unfortunately. Shame... So surely somebody out there has figured out how to add this comic? Right?

> David Revoy
@davidrevoy@framapiaf.org
@obisandwich Hey, no idea; I discover the Seeneva project with your toot. From the frontpage of the website, they are already familiar with Pepper&Carrot : https://seeneva.app/ , you should try to ask them. 

https://framapiaf.org/@davidrevoy/107524219149315954

**Comment by Zellius** [comment]
Hi, @ObiSandwich ! Right now **Seeneva** is only working with offline sources, like **CBZ** or **CBR** files.  They are just images packed into zip or rar archives. So you need to download all images from the website and pack them into one of supported formats. The archive should contains only images without any folders. Now you can import the archive into the app.

Sorry, I don't have any PC with me at the moment to show you an example.

I hope it helps you. 

Happy New Year! :)

**Comment by ObiSandwich** [comment]
Thank you - got it working :) Amazing app! Good job and keep up the good work :)

Happy New Year!
