### ISSUE TITLE
Translate readme to Japanese

### ISSUE THREAD

**Issue by kuragehimekurara1** [Seeneva/seeneva-reader-android#75]
I would like to translate Seeneva's readme into Japanese, what should I do?  Also, I translated the Seeeneva app into Japanese on weblate, so please add it.

**Comment by kuragehimekurara1** [comment]
Confirmed!

**Comment by kuragehimekurara1** [comment]
One more suggestion, but how about creating a Seeneva discord server?  If you create it, you will create it yourself!

**Comment by Zellius** [comment]
Yeah, I was thinking to create an [element.io](https://element.io) Space/Room. But Discord is indeed more mainstream so it can be more useful. Thanks, I will create it.

**Comment by kuragehimekurara1** [comment]
Is Zellius creating the discord server, not yourself (kuragehime)?

**Comment by kuragehimekurara1** [comment]
https://discord.gg/kPsWnJEYhG
 I created a discord server for the time being
