### ISSUE TITLE
Latest release not on F-Droid!

### ISSUE THREAD

**Issue by ObiSandwich** [Seeneva/seeneva-reader-android#80]
Cant see latest release on F-Droid! Any plans to push this to F-Droid please?

**Comment by Zellius** [comment]
Hi! Yes, thanks to F-Droid maintainers the new version is [merged](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12082) and should be available soon! :+1:

**Comment by Zellius** [comment]
And here we go! The last version is [published](https://f-droid.org/en/packages/app.seeneva.reader/) to F-Droid.
