### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by xmha97** [Seeneva/seeneva-reader-android#85]
Please add the dark mode. (Like picture below)

![Screenshot_2022-11-14-13-23-05-397_app.seeneva.reader.jpg](https://user-images.githubusercontent.com/23485114/201629978-81ea8e1d-9fbf-48be-8b17-3ba35bcbe951.jpg)

**Comment by Zellius** [comment]
Thank you! 

Yes, I will implement it.

But the project already has related feature request #41 . So I will close this issue in favour of the first one.
